const questionBank = [
    // ---------------- Architecture ----------------
    {
        id: 1,
        domain: "Architecture",
        type: "multi_select",
        difficulty: "medium",
        scenario: "A global enterprise manages 200,000 endpoints across multiple regions.",
        question: "Which statements describe Tanium’s peer-to-peer chain architecture?",
        answers: [
            "Endpoints pass results along the chain",
            "Direct polling of each endpoint by the server",
            "Data aggregation reduces network traffic",
            "Requires broadcast queries for every question"
        ],
        correct: [0, 2],
        explanation: "Tanium’s linear chain architecture aggregates data and reduces traffic by passing results peer-to-peer.",
        tags: ["architecture", "peer-to-peer", "scale"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 2,
        domain: "Architecture",
        type: "true_false",
        difficulty: "easy",
        scenario: "Discussing endpoint communication.",
        question: "Tanium endpoints always send data directly to the central server first.",
        answers: ["True", "False"],
        correct: 1,
        explanation: "Endpoints communicate peer-to-peer first, reducing central server load.",
        tags: ["architecture", "communication"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 3,
        domain: "Architecture",
        type: "multiple",
        difficulty: "medium",
        scenario: "Assessing how Tanium minimizes WAN traffic.",
        question: "Which components help reduce WAN latency?",
        answers: [
            "Zones",
            "Broadcast header messages",
            "Relay chains",
            "Direct server polling"
        ],
        correct: [0, 2],
        explanation: "Zones and relay chains reduce WAN traffic and improve performance.",
        tags: ["architecture", "WAN", "zones"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 4,
        domain: "Architecture",
        type: "multiple",
        difficulty: "medium",
        scenario: "Designing Tanium for segmented networks.",
        question: "Which elements help in segmented or remote networks?",
        answers: [
            "Tanium Zones",
            "Primary server only",
            "Relay chains",
            "Always-on VPN requirement"
        ],
        correct: [0, 2],
        explanation: "Zones and relay chains allow efficient data flow in segmented networks.",
        tags: ["architecture", "remote networks"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 5,
        domain: "Architecture",
        type: "true_false",
        difficulty: "easy",
        scenario: "Instructor explains Tanium design.",
        question: "Tanium’s peer chain model causes higher network usage than traditional polling.",
        answers: ["True", "False"],
        correct: 1,
        explanation: "Tanium’s peer chain model reduces network usage by aggregating results.",
        tags: ["architecture", "efficiency"],
        examWeight: 1,
        shuffleAnswers: true
    },
    // ---------------- Core Objects ----------------
    {
        id: 6,
        domain: "Core Objects",
        type: "multiple",
        difficulty: "easy",
        scenario: "A technician needs endpoint inventory data.",
        question: "Which object retrieves data from endpoints?",
        answers: ["Sensor", "Package", "Action", "Label"],
        correct: [0],
        explanation: "Sensors collect data from endpoints in real time.",
        tags: ["core-objects", "sensors"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 7,
        domain: "Core Objects",
        type: "multiple",
        difficulty: "easy",
        scenario: "Automating endpoint repairs.",
        question: "Which object contains executable scripts?",
        answers: ["Package", "Sensor", "Saved Question", "Trend"],
        correct: [0],
        explanation: "Packages contain scripts or installers executed on endpoints.",
        tags: ["core-objects", "packages"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 8,
        domain: "Core Objects",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Building reusable components.",
        question: "Which objects can be reused across multiple tasks?",
        answers: ["Package", "Saved Question", "Sensor", "Label"],
        correct: [0, 1, 3],
        explanation: "Packages, Saved Questions, and Labels can be reused in workflows.",
        tags: ["core-objects", "reuse"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 9,
        domain: "Core Objects",
        type: "true_false",
        difficulty: "easy",
        scenario: "Discussing persistence of objects.",
        question: "Saved Questions automatically update results without user input once saved.",
        answers: ["True", "False"],
        correct: 1,
        explanation: "Saved Questions store queries but don’t refresh automatically without execution.",
        tags: ["core-objects", "saved-questions"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 10,
        domain: "Core Objects",
        type: "scenario",
        difficulty: "medium",
        scenario: "An analyst needs to run a script after collecting audit data.",
        question: "Which object sequence is correct to collect data then execute a script?",
        answers: [
            "Sensor then Package",
            "Package then Saved Question",
            "Action then Sensor",
            "Label then Trend"
        ],
        correct: [0],
        explanation: "First collect data with a sensor, then execute actions via a package.",
        tags: ["core-objects", "workflow"],
        examWeight: 2,
        shuffleAnswers: true
    },
    // ---------------- Interact / Queries ----------------
    {
        id: 11,
        domain: "Interact",
        type: "multiple",
        difficulty: "easy",
        scenario: "Checking tools for live data queries.",
        question: "Which Tanium module allows real-time endpoint queries?",
        answers: ["Interact", "Asset", "Deploy", "Connect"],
        correct: [0],
        explanation: "Interact is used for live endpoint questions.",
        tags: ["interact", "live"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 12,
        domain: "Queries",
        type: "multiple",
        difficulty: "medium",
        scenario: "Combining sensors in a query.",
        question: "Which query syntax retrieves OS and hostname together?",
        answers: [
            "Ask OS and Computer Name from all machines",
            "Ask OS then filter Hostname",
            "Deploy a package to collect both",
            "Use Connect to query both"
        ],
        correct: [0],
        explanation: "Interact supports querying multiple sensors together.",
        tags: ["queries", "syntax"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 13,
        domain: "Queries",
        type: "true_false",
        difficulty: "medium",
        scenario: "Filtering query results.",
        question: "The 'with' clause limits results to specific sensor conditions.",
        answers: ["True", "False"],
        correct: 0,
        explanation: "The 'with' clause filters results using sensor values.",
        tags: ["queries", "filter"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 14,
        domain: "Queries",
        type: "scenario",
        difficulty: "hard",
        scenario: "An operator needs results from endpoints with low disk space and high CPU usage.",
        question: "Which query expression accomplishes this?",
        answers: [
            "Ask 'System Disk Free Space' and 'CPU Load' with 'System Disk Free Space < 10%'",
            "Ask CPU then ask disk separately",
            "Deploy monitoring package",
            "Export to Connect"
        ],
        correct: [0],
        explanation: "Combine multiple sensors with conditions using Interact.",
        tags: ["queries", "scenario"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 15,
        domain: "Interact",
        type: "multiple",
        difficulty: "medium",
        scenario: "Leveraging saved questions.",
        question: "Which benefit do Saved Questions provide?",
        answers: [
            "Instant execution of predefined queries",
            "Automatic patch deployment",
            "Baseline configuration enforcement",
            "Endpoint reboot scheduling"
        ],
        correct: [0],
        explanation: "Saved Questions speed up repeated queries.",
        tags: ["interact", "saved-questions"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 16,
        domain: "Modules",
        type: "multiple",
        difficulty: "easy",
        scenario: "An IT team needs to deploy patches across endpoints.",
        question: "Which module manages patch and software deployment?",
        answers: ["Deploy", "Interact", "Connect", "Asset"],
        correct: [0],
        explanation: "Deploy manages software and patch distribution across endpoints.",
        tags: ["modules", "deploy"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 17,
        domain: "Modules",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Security wants dashboards and historical trends.",
        question: "Which modules provide dashboards and trend visualization?",
        answers: ["Trends", "Asset", "Connect", "Interact"],
        correct: [0],
        explanation: "Trends provides time-based dashboards and analysis.",
        tags: ["modules", "trends"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 18,
        domain: "Modules",
        type: "multiple",
        difficulty: "easy",
        scenario: "A company wants a full inventory of hardware and software.",
        question: "Which module provides endpoint asset inventory?",
        answers: ["Asset", "Deploy", "Connect", "Interact"],
        correct: [0],
        explanation: "Asset collects and manages hardware and software inventory.",
        tags: ["modules", "asset"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 19,
        domain: "Modules",
        type: "multiple",
        difficulty: "medium",
        scenario: "A security team wants to detect unmanaged devices.",
        question: "Which module identifies endpoints without the Tanium client?",
        answers: ["Discover", "Asset", "Deploy", "Trends"],
        correct: [0],
        explanation: "Discover scans networks to find unmanaged devices.",
        tags: ["modules", "discover"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 20,
        domain: "RBAC",
        type: "multi_select",
        difficulty: "medium",
        scenario: "An administrator is configuring user permissions.",
        question: "Which capabilities are controlled via RBAC?",
        answers: [
            "Who can ask questions",
            "Who can run actions",
            "Which computer groups a user can access",
            "Network firewall configuration"
        ],
        correct: [0, 1, 2],
        explanation: "RBAC controls permissions related to actions, questions, and scope.",
        tags: ["security", "rbac"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 21,
        domain: "Sensors",
        type: "multiple",
        difficulty: "medium",
        scenario: "A SOC analyst needs active process info.",
        question: "Which sensor returns running processes on endpoints?",
        answers: ["Running Processes", "Process Monitor", "Active Tasks", "Application Status"],
        correct: [0],
        explanation: "The 'Running Processes' sensor retrieves active process data.",
        tags: ["sensors", "processes"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 22,
        domain: "Sensors",
        type: "multiple",
        difficulty: "medium",
        scenario: "An administrator wants disk usage info.",
        question: "Which sensor provides available disk space information?",
        answers: ["System Disk Free Space", "Disk Inventory", "Drive Status", "Storage Monitor"],
        correct: [0],
        explanation: "System Disk Free Space reports available disk capacity.",
        tags: ["sensors", "disk"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 23,
        domain: "Actions",
        type: "multiple",
        difficulty: "medium",
        scenario: "Triggering remediation across endpoints.",
        question: "What mechanism executes a package on endpoints?",
        answers: ["Action", "Sensor", "Label", "Trend"],
        correct: [0],
        explanation: "Packages are executed via Actions in Tanium.",
        tags: ["actions", "execution"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 24,
        domain: "Connect",
        type: "multiple",
        difficulty: "medium",
        scenario: "Exporting endpoint data to SIEM.",
        question: "Which component defines where exported data is sent?",
        answers: ["Destination", "Source", "Sensor", "Board"],
        correct: [0],
        explanation: "Destination defines the target receiving system in Connect jobs.",
        tags: ["connect", "export"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 25,
        domain: "Connect",
        type: "multiple",
        difficulty: "medium",
        scenario: "Configuring data export.",
        question: "Which component defines the origin of exported data?",
        answers: ["Source", "Destination", "Sensor", "Trend"],
        correct: [0],
        explanation: "Source defines which data is exported from Tanium.",
        tags: ["connect", "export"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 26,
        domain: "Investigation",
        type: "multiple",
        difficulty: "medium",
        scenario: "During an incident, an analyst needs to run commands on endpoints.",
        question: "Which capability allows direct endpoint investigation?",
        answers: ["Live Response", "Deploy", "Asset", "Trends"],
        correct: [0],
        explanation: "Live Response allows interactive investigation on endpoints.",
        tags: ["investigation", "live-response"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 27,
        domain: "Grouping",
        type: "multiple",
        difficulty: "medium",
        scenario: "Grouping endpoints dynamically by OS.",
        question: "Which feature enables dynamic grouping?",
        answers: ["Labels", "Packages", "Boards", "Deploy"],
        correct: [0],
        explanation: "Labels dynamically group endpoints based on sensor conditions.",
        tags: ["grouping", "labels"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 28,
        domain: "Modules",
        type: "multi_select",
        difficulty: "hard",
        scenario: "An admin wants patch deployment and inventory.",
        question: "Which modules help manage software and hardware info?",
        answers: ["Deploy", "Asset", "Trends", "Connect"],
        correct: [0, 1],
        explanation: "Deploy manages software, Asset collects hardware/software info.",
        tags: ["modules", "inventory"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 29,
        domain: "Sensors",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Monitoring security events.",
        question: "Which sensors can be used to monitor active threats?",
        answers: ["Running Processes", "Active Sessions", "Installed Software", "CPU Load"],
        correct: [0, 1, 2],
        explanation: "These sensors provide insight into potentially malicious activity.",
        tags: ["sensors", "security"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 30,
        domain: "Actions",
        type: "multiple",
        difficulty: "hard",
        scenario: "Remediation of malware infection across endpoints.",
        question: "Which mechanism executes a clean-up package on endpoints?",
        answers: ["Action", "Sensor", "Label", "Board"],
        correct: [0],
        explanation: "Actions execute packages for remediation across endpoints.",
        tags: ["actions", "remediation"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 31,
        domain: "Connect",
        type: "scenario",
        difficulty: "medium",
        scenario: "A SOC wants endpoint logs in Splunk.",
        question: "How should the Connect job be configured to export Windows event logs?",
        answers: [
            "Define Source as 'Windows Event Logs', Destination as Splunk",
            "Deploy package to collect logs then Connect",
            "Use Trends to export logs",
            "Ask Interact for logs then export"
        ],
        correct: [0],
        explanation: "Source defines which data to export; Destination defines where it goes.",
        tags: ["connect", "scenario"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 32,
        domain: "RBAC",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Configuring admin and analyst access.",
        question: "Which RBAC settings are valid?",
        answers: [
            "Grant permission to ask questions",
            "Grant permission to run actions",
            "Restrict access to specific computer groups",
            "Change network firewall rules"
        ],
        correct: [0, 1, 2],
        explanation: "RBAC controls questions, actions, and scope, not network firewalls.",
        tags: ["security", "rbac"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 33,
        domain: "Modules",
        type: "multiple",
        difficulty: "medium",
        scenario: "Executives want dashboards with trends and metrics.",
        question: "Which module provides these dashboards?",
        answers: ["Trends", "Connect", "Deploy", "Interact"],
        correct: [0],
        explanation: "Trends provides historical dashboards and time-based visualizations.",
        tags: ["modules", "trends"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 34,
        domain: "Interact",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Analyst wants to combine sensors to identify outdated software and low disk space.",
        question: "Which approaches can be used?",
        answers: [
            "Ask 'Installed Software' and 'System Disk Free Space' from all machines",
            "Ask Installed Software then Disk Space separately",
            "Deploy package to collect both",
            "Export data separately to Connect"
        ],
        correct: [0],
        explanation: "Interact allows combining multiple sensors in one live question.",
        tags: ["interact", "scenario"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 35,
        domain: "Core Objects",
        type: "scenario",
        difficulty: "hard",
        scenario: "A SOC wants to automate repetitive remediation and inventory tasks.",
        question: "Which object sequence correctly combines collection and execution?",
        answers: [
            "Sensor → Saved Question → Action",
            "Package → Sensor → Board",
            "Action → Label → Trend",
            "Saved Question → Deploy → Asset"
        ],
        correct: [0],
        explanation: "Collect with Sensor, save query with Saved Question, execute with Action.",
        tags: ["core-objects", "workflow"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 36,
        domain: "Sensors",
        type: "multiple",
        difficulty: "medium",
        scenario: "Checking endpoint process information.",
        question: "Which sensors return active processes or sessions?",
        answers: ["Running Processes", "Active Sessions", "CPU Load", "Memory Usage"],
        correct: [0, 1],
        explanation: "Running Processes and Active Sessions sensors provide this information.",
        tags: ["sensors", "monitoring"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 37,
        domain: "Sensors",
        type: "multiple",
        difficulty: "medium",
        scenario: "Checking endpoint storage usage.",
        question: "Which sensors provide disk and storage information?",
        answers: ["System Disk Free Space", "Drive Status", "CPU Load", "Memory Usage"],
        correct: [0, 1],
        explanation: "System Disk Free Space and Drive Status provide storage metrics.",
        tags: ["sensors", "disk"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 38,
        domain: "Actions",
        type: "multi_select",
        difficulty: "hard",
        scenario: "Applying patches and scripts across endpoints.",
        question: "Which methods use Actions for execution?",
        answers: ["Deploy Package", "Execute Script", "Label Assignment", "Trend Analysis"],
        correct: [0, 1],
        explanation: "Actions execute Packages or Scripts on endpoints.",
        tags: ["actions", "execution"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 39,
        domain: "Modules",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Maintaining endpoint security posture.",
        question: "Which modules support endpoint compliance and inventory?",
        answers: ["Asset", "Deploy", "Connect", "Trends"],
        correct: [0, 1],
        explanation: "Asset provides inventory, Deploy manages patch compliance.",
        tags: ["modules", "security"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 40,
        domain: "Connect",
        type: "multiple",
        difficulty: "medium",
        scenario: "Exporting threat intel to SIEM.",
        question: "Which Connect components must be defined?",
        answers: ["Source", "Destination", "Board", "Trend"],
        correct: [0, 1],
        explanation: "Connect requires defining both Source and Destination for export.",
        tags: ["connect", "export"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 41,
        domain: "Grouping",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Dynamically grouping endpoints for patching.",
        question: "Which features allow dynamic grouping?",
        answers: ["Labels", "Saved Questions", "Packages", "Sensors"],
        correct: [0, 3],
        explanation: "Labels and sensor conditions allow dynamic grouping of endpoints.",
        tags: ["grouping", "labels"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 42,
        domain: "Investigation",
        type: "scenario",
        difficulty: "hard",
        scenario: "Investigating suspicious endpoint activity.",
        question: "Which approach uses Tanium for live investigation?",
        answers: [
            "Live Response with sensors",
            "Deploy package to collect logs",
            "Ask Interact then export to Connect",
            "Use Trends to view historical activity"
        ],
        correct: [0],
        explanation: "Live Response allows direct interactive investigation on endpoints.",
        tags: ["investigation", "live-response"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 43,
        domain: "RBAC",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Assigning granular user permissions.",
        question: "Which permissions can be managed via RBAC?",
        answers: [
            "Ask Questions",
            "Run Actions",
            "Access specific computers",
            "Install Tanium client"
        ],
        correct: [0, 1, 2],
        explanation: "RBAC controls questions, actions, and endpoint scope, but not client installation.",
        tags: ["security", "rbac"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 44,
        domain: "Modules",
        type: "multiple",
        difficulty: "medium",
        scenario: "Trend analysis and reporting.",
        question: "Which module provides historical endpoint data trends?",
        answers: ["Trends", "Deploy", "Connect", "Asset"],
        correct: [0],
        explanation: "Trends provides dashboards and time-based analysis.",
        tags: ["modules", "trends"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 45,
        domain: "Interact",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Querying multiple endpoint sensors.",
        question: "Which queries combine multiple sensors?",
        answers: [
            "Ask 'Installed Software' and 'System Disk Free Space'",
            "Ask Software then Disk separately",
            "Deploy package to collect both",
            "Export separately to Connect"
        ],
        correct: [0],
        explanation: "Interact supports multiple sensors in one live question.",
        tags: ["interact", "queries"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 46,
        domain: "Core Objects",
        type: "multi_select",
        difficulty: "hard",
        scenario: "Automating auditing and remediation.",
        question: "Which objects can be combined in a workflow?",
        answers: ["Sensor", "Saved Question", "Action", "Board"],
        correct: [0, 1, 2],
        explanation: "Collect with Sensor, save queries, execute via Actions.",
        tags: ["core-objects", "workflow"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 47,
        domain: "Sensors",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Monitoring system performance.",
        question: "Which sensors provide performance metrics?",
        answers: ["CPU Load", "Memory Usage", "Disk Free Space", "Active Sessions"],
        correct: [0, 1, 2],
        explanation: "CPU, memory, and disk sensors monitor performance.",
        tags: ["sensors", "performance"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 48,
        domain: "Actions",
        type: "multi_select",
        difficulty: "hard",
        scenario: "Mass remediation execution.",
        question: "Which Actions methods execute tasks?",
        answers: ["Deploy Package", "Run Script", "Assign Label", "Trend Analysis"],
        correct: [0, 1],
        explanation: "Actions execute Packages or Scripts on endpoints.",
        tags: ["actions", "execution"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 49,
        domain: "Modules",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Ensuring endpoint compliance.",
        question: "Which modules monitor compliance and inventory?",
        answers: ["Deploy", "Asset", "Connect", "Trends"],
        correct: [0, 1],
        explanation: "Deploy and Asset manage software/hardware compliance and inventory.",
        tags: ["modules", "compliance"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 50,
        domain: "Connect",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Exporting data to SIEM platforms.",
        question: "Which Connect components must be configured?",
        answers: ["Source", "Destination", "Sensor", "Board"],
        correct: [0, 1],
        explanation: "Connect requires both Source (data origin) and Destination (target system).",
        tags: ["connect", "export"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 51,
        domain: "Architecture",
        type: "multiple",
        difficulty: "medium",
        scenario: "A global enterprise wants efficient data collection across regions.",
        question: "Which features of Tanium architecture support efficient querying?",
        answers: ["Linear chain P2P", "Result aggregation", "Centralized polling", "Broadcast to all endpoints"],
        correct: [0, 1],
        explanation: "Linear chain peer-to-peer and aggregation reduce network traffic and speed up responses.",
        tags: ["architecture", "efficiency"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 52,
        domain: "Architecture",
        type: "true_false",
        difficulty: "easy",
        scenario: "Understanding endpoint communication.",
        question: "Endpoints always send data directly to the Tanium server.",
        answers: ["True", "False"],
        correct: 1,
        explanation: "Endpoints communicate peer-to-peer along a chain instead of always going directly to the server.",
        tags: ["architecture", "p2p"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 53,
        domain: "Core Objects",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Storing queries and scripts for reuse.",
        question: "Which objects allow reuse of queries or scripts?",
        answers: ["Saved Question", "Package", "Board", "Trend"],
        correct: [0, 1],
        explanation: "Saved Questions store queries; Packages store scripts that can be executed repeatedly.",
        tags: ["core-objects", "reuse"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 54,
        domain: "Interact",
        type: "multiple",
        difficulty: "medium",
        scenario: "Asking live questions across endpoints.",
        question: "Which module allows live querying of endpoint data?",
        answers: ["Interact", "Deploy", "Connect", "Asset"],
        correct: [0],
        explanation: "Interact is the module for live question and data retrieval.",
        tags: ["interact", "queries"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 55,
        domain: "Queries",
        type: "multi_select",
        difficulty: "hard",
        scenario: "Filtering endpoint data using sensor values.",
        question: "Which clauses can be used to filter query results?",
        answers: ["with", "where", "select", "from"],
        correct: [0, 1],
        explanation: "The 'with' and 'where' clauses filter query results based on sensor conditions.",
        tags: ["queries", "filter"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 56,
        domain: "Modules",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Monitoring hardware and software compliance.",
        question: "Which modules support inventory and compliance?",
        answers: ["Asset", "Deploy", "Connect", "Trends"],
        correct: [0, 1],
        explanation: "Asset provides inventory, Deploy manages software compliance and patches.",
        tags: ["modules", "compliance"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 57,
        domain: "Modules",
        type: "multiple",
        difficulty: "easy",
        scenario: "A SOC team needs dashboards for historical data.",
        question: "Which module provides historical dashboards?",
        answers: ["Trends", "Asset", "Deploy", "Connect"],
        correct: [0],
        explanation: "Trends allows analysis of historical endpoint metrics.",
        tags: ["modules", "trends"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 58,
        domain: "RBAC",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Defining user roles and permissions.",
        question: "Which actions can RBAC control?",
        answers: ["Ask Questions", "Run Actions", "Access Computer Groups", "Change Firewall"],
        correct: [0, 1, 2],
        explanation: "RBAC controls question, action, and scope permissions, not firewall configuration.",
        tags: ["security", "rbac"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 59,
        domain: "Sensors",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Monitoring active processes and sessions.",
        question: "Which sensors provide security-relevant monitoring?",
        answers: ["Running Processes", "Active Sessions", "CPU Load", "Installed Software"],
        correct: [0, 1, 3],
        explanation: "These sensors help monitor potentially malicious activity on endpoints.",
        tags: ["sensors", "security"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 60,
        domain: "Actions",
        type: "multi_select",
        difficulty: "hard",
        scenario: "Mass deployment of remediation scripts.",
        question: "Which methods use Actions to execute tasks?",
        answers: ["Deploy Package", "Run Script", "Assign Label", "Trend Analysis"],
        correct: [0, 1],
        explanation: "Actions can execute packages or scripts across multiple endpoints.",
        tags: ["actions", "execution"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 61,
        domain: "Connect",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Exporting endpoint logs to SIEM.",
        question: "Which components must be configured?",
        answers: ["Source", "Destination", "Board", "Trend"],
        correct: [0, 1],
        explanation: "Connect jobs require both Source and Destination to export data.",
        tags: ["connect", "export"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 62,
        domain: "Grouping",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Dynamic grouping for patch deployment.",
        question: "Which features allow dynamic endpoint grouping?",
        answers: ["Labels", "Saved Questions", "Packages", "Sensors"],
        correct: [0, 3],
        explanation: "Labels and sensor conditions enable dynamic grouping.",
        tags: ["grouping", "dynamic"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 63,
        domain: "Investigation",
        type: "scenario",
        difficulty: "hard",
        scenario: "Investigating suspicious activity on endpoints.",
        question: "Which approach allows live investigation?",
        answers: [
            "Live Response with sensors",
            "Deploy package to collect logs",
            "Ask Interact then export",
            "Use Trends for history"
        ],
        correct: [0],
        explanation: "Live Response allows direct, interactive endpoint investigation.",
        tags: ["investigation", "live-response"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 64,
        domain: "Modules",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Maintaining endpoint health and metrics.",
        question: "Which modules provide monitoring and reporting?",
        answers: ["Trends", "Asset", "Deploy", "Connect"],
        correct: [0, 1],
        explanation: "Trends gives dashboards; Asset tracks endpoint inventory and status.",
        tags: ["modules", "monitoring"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 65,
        domain: "Core Objects",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Automating remediation workflows.",
        question: "Which objects can be combined for workflow automation?",
        answers: ["Sensor", "Saved Question", "Action", "Board"],
        correct: [0, 1, 2],
        explanation: "Sensors collect data, Saved Questions store queries, Actions execute packages.",
        tags: ["core-objects", "workflow"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 66,
        domain: "Sensors",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Collecting system performance metrics.",
        question: "Which sensors provide performance data?",
        answers: ["CPU Load", "Memory Usage", "Disk Free Space", "Network Usage"],
        correct: [0, 1, 2],
        explanation: "CPU, memory, and disk sensors monitor system performance.",
        tags: ["sensors", "performance"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 67,
        domain: "Actions",
        type: "multi_select",
        difficulty: "hard",
        scenario: "Executing mass patch deployment.",
        question: "Which Actions methods execute packages or scripts?",
        answers: ["Deploy Package", "Run Script", "Assign Label", "Trend Analysis"],
        correct: [0, 1],
        explanation: "Actions can run scripts or packages on endpoints.",
        tags: ["actions", "execution"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 68,
        domain: "Interact",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Combining multiple sensors in a query.",
        question: "Which methods allow combining sensors?",
        answers: [
            "Ask 'Installed Software' and 'System Disk Free Space'",
            "Ask Software then Disk separately",
            "Deploy package to collect both",
            "Export separately to Connect"
        ],
        correct: [0],
        explanation: "Interact supports combining multiple sensors in one live question.",
        tags: ["interact", "queries"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 69,
        domain: "RBAC",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Defining granular permissions.",
        question: "Which permissions can RBAC manage?",
        answers: ["Ask Questions", "Run Actions", "Access Computer Groups", "Install Tanium Client"],
        correct: [0, 1, 2],
        explanation: "RBAC manages question, action, and computer group access, not client installation.",
        tags: ["security", "rbac"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 70,
        domain: "Modules",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Monitoring endpoint compliance and inventory.",
        question: "Which modules support endpoint compliance?",
        answers: ["Deploy", "Asset", "Connect", "Trends"],
        correct: [0, 1],
        explanation: "Deploy manages patches; Asset manages hardware/software inventory.",
        tags: ["modules", "compliance"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 71,
        domain: "Sensors",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Monitoring endpoint security state.",
        question: "Which sensors can help detect potential security risks?",
        answers: ["Running Processes", "Installed Software", "Active Sessions", "CPU Load"],
        correct: [0, 1, 2],
        explanation: "Running Processes, Installed Software, and Active Sessions provide visibility for security monitoring.",
        tags: ["sensors", "security"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 72,
        domain: "Actions",
        type: "multiple",
        difficulty: "hard",
        scenario: "Executing remediation across multiple endpoints.",
        question: "What object executes packages or scripts on endpoints?",
        answers: ["Action", "Sensor", "Label", "Board"],
        correct: [0],
        explanation: "Actions execute packages or scripts to endpoints.",
        tags: ["actions", "execution"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 73,
        domain: "Connect",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Exporting logs to multiple systems.",
        question: "Which components are needed for exporting data via Connect?",
        answers: ["Source", "Destination", "Sensor", "Board"],
        correct: [0, 1],
        explanation: "Connect requires Source and Destination to export data.",
        tags: ["connect", "export"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 74,
        domain: "Grouping",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Dynamic grouping for reporting and deployment.",
        question: "Which Tanium features allow dynamic grouping of endpoints?",
        answers: ["Labels", "Sensors", "Saved Questions", "Actions"],
        correct: [0, 1],
        explanation: "Labels and sensor conditions enable dynamic endpoint grouping.",
        tags: ["grouping", "dynamic"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 75,
        domain: "Investigation",
        type: "scenario",
        difficulty: "hard",
        scenario: "A security analyst needs to inspect a compromised endpoint.",
        question: "Which method provides live, interactive investigation?",
        answers: ["Live Response", "Deploy Package", "Interact Query", "Trend Dashboard"],
        correct: [0],
        explanation: "Live Response allows direct interactive investigation of endpoints.",
        tags: ["investigation", "live-response"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 76,
        domain: "Modules",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Monitoring and reporting endpoint metrics.",
        question: "Which modules provide visibility into endpoint metrics?",
        answers: ["Trends", "Asset", "Deploy", "Connect"],
        correct: [0, 1],
        explanation: "Trends provides historical dashboards; Asset provides inventory and status.",
        tags: ["modules", "monitoring"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 77,
        domain: "Core Objects",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Automating responses based on endpoint data.",
        question: "Which objects can be combined to automate actions?",
        answers: ["Sensor", "Saved Question", "Action", "Board"],
        correct: [0, 1, 2],
        explanation: "Sensors collect data, Saved Questions store queries, Actions execute packages.",
        tags: ["core-objects", "automation"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 78,
        domain: "Sensors",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Collecting system metrics for performance monitoring.",
        question: "Which sensors provide system performance metrics?",
        answers: ["CPU Load", "Memory Usage", "Disk Free Space", "Running Processes"],
        correct: [0, 1, 2],
        explanation: "CPU Load, Memory Usage, and Disk Free Space provide key performance data.",
        tags: ["sensors", "performance"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 79,
        domain: "Actions",
        type: "multi_select",
        difficulty: "hard",
        scenario: "Mass remediation deployment.",
        question: "Which methods can be executed using Actions?",
        answers: ["Deploy Package", "Run Script", "Assign Label", "Trend Analysis"],
        correct: [0, 1],
        explanation: "Actions execute scripts or packages across multiple endpoints.",
        tags: ["actions", "execution"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 80,
        domain: "Interact",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Combining multiple sensors in a single question.",
        question: "Which approaches correctly combine sensors?",
        answers: [
            "Ask 'Installed Software' and 'System Disk Free Space'",
            "Ask Software then Disk separately",
            "Deploy package to collect both",
            "Export separately to Connect"
        ],
        correct: [0],
        explanation: "Interact allows combining multiple sensors in a single live question.",
        tags: ["interact", "queries"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 81,
        domain: "RBAC",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Assigning roles and permissions.",
        question: "Which permissions can be controlled via RBAC?",
        answers: ["Ask Questions", "Run Actions", "Access Computer Groups", "Install Tanium Client"],
        correct: [0, 1, 2],
        explanation: "RBAC manages questions, actions, and scope, but not client installation.",
        tags: ["security", "rbac"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 82,
        domain: "Modules",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Ensuring endpoint compliance.",
        question: "Which modules help maintain endpoint compliance?",
        answers: ["Deploy", "Asset", "Connect", "Trends"],
        correct: [0, 1],
        explanation: "Deploy manages patches; Asset tracks inventory for compliance.",
        tags: ["modules", "compliance"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 83,
        domain: "Sensors",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Monitoring software and processes.",
        question: "Which sensors are useful for detecting suspicious activity?",
        answers: ["Running Processes", "Installed Software", "Active Sessions", "CPU Load"],
        correct: [0, 1, 2],
        explanation: "Monitoring processes, software, and sessions helps detect anomalies.",
        tags: ["sensors", "security"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 84,
        domain: "Actions",
        type: "multi_select",
        difficulty: "hard",
        scenario: "Executing scripts across endpoints.",
        question: "Which methods use Actions to run tasks?",
        answers: ["Deploy Package", "Run Script", "Assign Label", "Trend Analysis"],
        correct: [0, 1],
        explanation: "Actions execute scripts or packages across endpoints.",
        tags: ["actions", "execution"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 85,
        domain: "Connect",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Exporting endpoint data to SIEM tools.",
        question: "Which components must be configured in a Connect job?",
        answers: ["Source", "Destination", "Sensor", "Board"],
        correct: [0, 1],
        explanation: "Connect requires Source and Destination to function correctly.",
        tags: ["connect", "export"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 86,
        domain: "Grouping",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Dynamic endpoint grouping for policies.",
        question: "Which features enable dynamic grouping?",
        answers: ["Labels", "Sensors", "Saved Questions", "Actions"],
        correct: [0, 1],
        explanation: "Labels and sensor conditions allow dynamic grouping of endpoints.",
        tags: ["grouping", "dynamic"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 87,
        domain: "Investigation",
        type: "scenario",
        difficulty: "hard",
        scenario: "Investigating potential malware infection.",
        question: "Which Tanium feature allows live investigation?",
        answers: ["Live Response", "Deploy Package", "Interact Query", "Trend Dashboard"],
        correct: [0],
        explanation: "Live Response allows direct interaction with endpoints for investigation.",
        tags: ["investigation", "live-response"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 88,
        domain: "Modules",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Monitoring endpoint health.",
        question: "Which modules provide endpoint monitoring dashboards?",
        answers: ["Trends", "Asset", "Deploy", "Connect"],
        correct: [0, 1],
        explanation: "Trends provides dashboards; Asset provides inventory and status metrics.",
        tags: ["modules", "monitoring"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 89,
        domain: "Core Objects",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Automating routine tasks.",
        question: "Which objects can automate responses to endpoint data?",
        answers: ["Sensor", "Saved Question", "Action", "Board"],
        correct: [0, 1, 2],
        explanation: "Sensors collect data, Saved Questions store queries, Actions execute packages.",
        tags: ["core-objects", "automation"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 90,
        domain: "Sensors",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Collecting system performance metrics.",
        question: "Which sensors provide performance monitoring data?",
        answers: ["CPU Load", "Memory Usage", "Disk Free Space", "Network Usage"],
        correct: [0, 1, 2],
        explanation: "CPU, memory, and disk sensors provide critical system performance information.",
        tags: ["sensors", "performance"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 91,
        domain: "Actions",
        type: "multi_select",
        difficulty: "hard",
        scenario: "Mass deployment of software updates.",
        question: "Which methods execute tasks via Actions?",
        answers: ["Deploy Package", "Run Script", "Assign Label", "Trend Analysis"],
        correct: [0, 1],
        explanation: "Actions can deploy packages or run scripts across endpoints.",
        tags: ["actions", "execution"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 92,
        domain: "Interact",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Combining sensors for detailed queries.",
        question: "Which approaches allow combining multiple sensors in one question?",
        answers: [
            "Ask 'Installed Software' and 'System Disk Free Space'",
            "Ask separately then combine results",
            "Deploy package to collect both",
            "Export data separately to Connect"
        ],
        correct: [0],
        explanation: "Interact supports combining multiple sensors in a single question.",
        tags: ["interact", "queries"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 93,
        domain: "RBAC",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Configuring user permissions.",
        question: "Which permissions are controlled by RBAC?",
        answers: ["Ask Questions", "Run Actions", "Access Computer Groups", "Install Tanium Client"],
        correct: [0, 1, 2],
        explanation: "RBAC controls access to questions, actions, and computer groups, not client installation.",
        tags: ["security", "rbac"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 94,
        domain: "Modules",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Ensuring endpoint compliance and reporting.",
        question: "Which modules support endpoint compliance?",
        answers: ["Deploy", "Asset", "Connect", "Trends"],
        correct: [0, 1],
        explanation: "Deploy handles patches; Asset tracks hardware/software for compliance.",
        tags: ["modules", "compliance"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 95,
        domain: "Sensors",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Detecting suspicious activity on endpoints.",
        question: "Which sensors are useful for security monitoring?",
        answers: ["Running Processes", "Installed Software", "Active Sessions", "CPU Load"],
        correct: [0, 1, 2],
        explanation: "Monitoring processes, installed software, and sessions helps detect anomalies.",
        tags: ["sensors", "security"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 96,
        domain: "Actions",
        type: "multi_select",
        difficulty: "hard",
        scenario: "Executing remediation scripts on multiple endpoints.",
        question: "Which methods use Actions?",
        answers: ["Deploy Package", "Run Script", "Assign Label", "Trend Analysis"],
        correct: [0, 1],
        explanation: "Actions execute packages or scripts across endpoints.",
        tags: ["actions", "execution"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 97,
        domain: "Connect",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Exporting endpoint data to multiple destinations.",
        question: "Which components are required?",
        answers: ["Source", "Destination", "Sensor", "Board"],
        correct: [0, 1],
        explanation: "Connect requires Source and Destination configuration.",
        tags: ["connect", "export"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 98,
        domain: "Grouping",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Grouping endpoints dynamically based on sensor data.",
        question: "Which features enable dynamic grouping?",
        answers: ["Labels", "Sensors", "Saved Questions", "Actions"],
        correct: [0, 1],
        explanation: "Labels and sensors allow dynamic grouping.",
        tags: ["grouping", "dynamic"],
        examWeight: 1,
        shuffleAnswers: true
    },
    {
        id: 99,
        domain: "Investigation",
        type: "scenario",
        difficulty: "hard",
        scenario: "Investigating malware activity on endpoints.",
        question: "Which Tanium feature provides live endpoint investigation?",
        answers: ["Live Response", "Deploy Package", "Interact Query", "Trend Dashboard"],
        correct: [0],
        explanation: "Live Response allows direct, interactive endpoint investigation.",
        tags: ["investigation", "live-response"],
        examWeight: 2,
        shuffleAnswers: true
    },
    {
        id: 100,
        domain: "Modules",
        type: "multi_select",
        difficulty: "medium",
        scenario: "Monitoring endpoint metrics and compliance.",
        question: "Which modules provide dashboards and reporting?",
        answers: ["Trends", "Asset", "Deploy", "Connect"],
        correct: [0, 1],
        explanation: "Trends provides dashboards; Asset tracks inventory and metrics.",
        tags: ["modules", "monitoring"],
        examWeight: 2,
        shuffleAnswers: true
    }
];
